image: ksfmedia/diskho:lts-18.13

variables:
  DOCKER_DRIVER: overlay2
  GIT_SUBMODULE_STRATEGY: normal
  CI_SCRIPTS: "${CI_PROJECT_DIR}/infra/ci-scripts"

.mosaico-ci-variables: &mosaico-ci-vars
  SERVICE_NAME: mosaico
  MULTIPAPER: "true"

before_script:
  - eval `${CI_SCRIPTS}/prepare_stage_envvars.py ${CI_ENVIRONMENT_SLUG}`

stages:
  - branch-build
  - trunk-build
  - docker
  - deploy

# Build template
.branch-build-n-test:
  stage: branch-build
  except:
    - master
  script:
    # Install all project dependencies 
    - NODE_ENV=development yarn --cwd $CI_PROJECT_DIR install
    # Need to unset PUBLIC_URL for the tests to work
    - unset PUBLIC_URL
    - yarn --cwd $CI_PROJECT_DIR build
    - yarn --cwd $CI_PROJECT_DIR test

.build-app:
  stage: trunk-build
  environment: staging/$SERVICE_NAME
  only:
    - master
  artifacts:
    paths:
      - artifacts/
    when: always
    expire_in: 7 days
  script:
    - $CI_SCRIPTS/affresco/mosaico-build.sh

# Docker build template
.build-docker:
  stage: docker
  environment: staging/$SERVICE_NAME
  only:
    - master
  script:
    # docker build & push staging
    - cd $CI_PROJECT_DIR/artifacts/staging/$SERVICE_NAME
    - $CI_SCRIPTS/docker-build.sh
    - $CI_SCRIPTS/auth-gcloud.sh
    - $CI_SCRIPTS/docker-push.sh
    # docker buld & push production
    - eval `${CI_SCRIPTS}/prepare_stage_envvars.py production`
    - cd $CI_PROJECT_DIR/artifacts/production/$SERVICE_NAME
    - $CI_SCRIPTS/docker-build.sh
    - $CI_SCRIPTS/auth-gcloud.sh
    - $CI_SCRIPTS/docker-push.sh

# Deploy template
.deploy:
  stage: deploy
  environment: staging/$SERVICE_NAME
  only:
    - master
  script:
    - $CI_SCRIPTS/auth-gcloud.sh
    - LETTERA_URL=$LETTERA_INTERNAL $CI_SCRIPTS/kubernetes-deployment.sh
    - $CI_SCRIPTS/affresco/app-upload.sh

# Build apps
mosaico-branch-build:
  extends: .branch-build-n-test
  variables: *mosaico-ci-vars

mosaico-build:
  extends: .build-app
  variables: *mosaico-ci-vars

# Build docker images

mosaico-docker-build-hbl:
  extends: .build-docker
  needs: 
    - mosaico-build
  variables:
    SERVICE_NAME: mosaico-hbl

mosaico-docker-build-vn:
  extends: .build-docker
  needs: 
    - mosaico-build
  variables:
    SERVICE_NAME: mosaico-vn

mosaico-docker-build-on:
  extends: .build-docker
  needs: 
    - mosaico-build
  variables:
    SERVICE_NAME: mosaico-on

# Deploy Staging
deploy-mosaico-hbl-staging:
  extends: .deploy
  needs: 
    - mosaico-build
    - mosaico-docker-build-hbl
  variables:
    SERVICE_NAME: mosaico-hbl
    PAPER: "hbl"
    LETTERA_INTERNAL: "http://lettera/v4"

deploy-mosaico-vn-staging:
  extends: .deploy
  needs: 
    - mosaico-build
    - mosaico-docker-build-vn
  variables:
    SERVICE_NAME: mosaico-vn
    PAPER: "vn"
    LETTERA_INTERNAL: "http://lettera/v4"

deploy-mosaico-on-staging:
  extends: .deploy
  needs: 
    - mosaico-build
    - mosaico-docker-build-on
  variables:
    SERVICE_NAME: mosaico-on
    PAPER: "ön"
    LETTERA_INTERNAL: "http://lettera/v4"

# Deploy production

deploy-mosaico-hbl-production:
  extends: .deploy
  needs: 
    - mosaico-build
    - mosaico-docker-build-hbl
  environment: production/$SERVICE_NAME
  when: manual
  variables:
    SERVICE_NAME: mosaico-hbl
    PAPER: "hbl"
    LETTERA_INTERNAL: "http://lettera/v4"

deploy-mosaico-vn-production:
  extends: .deploy
  needs: 
    - mosaico-build
    - mosaico-docker-build-vn
  environment: production/$SERVICE_NAME
  when: manual
  variables:
    SERVICE_NAME: mosaico-vn
    PAPER: "vn"
    LETTERA_INTERNAL: "http://lettera/v4"

deploy-mosaico-on-production:
  extends: .deploy
  needs: 
    - mosaico-build
    - mosaico-docker-build-on
  environment: production/$SERVICE_NAME
  when: manual
  variables:
    SERVICE_NAME: mosaico-on
    PAPER: "ön"
    LETTERA_INTERNAL: "http://lettera/v4"
